### ISSUE TITLE
서비스를 보고 토큰을 사용할지, 세션을 사용할지 어떻게 판단하시나요?

### ISSUE THREAD

**Issue by hh830** [Coding-Crew-Forever/CS-Study#1]
토큰이나 세션을 사용하는 경우를 어떻게 판단하는지 이야기 해보고 싶어요

토큰과 세션의 차이가 아래와 같은 것은 이해했어요.

1. 세션은 데이터베이스 서버, 토큰은 클라이언트에 저장
2. 토큰이 세션보다 사이즈가 크다
3. 토큰은 확장성이 좋다
https://fierycoding.tistory.com/69

하지만 토큰이 세션의 단점을 보완한 것 같아 보이는데 세션이 사용되는 경우는 사이즈만 고려하면 되는 걸까요? 

다들 서비스를 보고 토큰을 사용할지, 세션을 사용할지 어떻게 구분하는지 궁금해요!
자유롭게 의견 달아주시면 감사하겠습니다 😊

**Comment by dnya0** [comment]
서버가 여러 개라면 토큰을 사용하는 것이 좋아요. 상태유지 관점에서도 토큰이 더 좋습니다.
세션은 서버에서 관리하지만 토큰은 클라이언트에서 관리하여 서버 부하가 적어요.

그 이야기는 토큰은 stateless하다는 뜻이에요!

예를 들어, 서버를 여러 대 운영해서 트래픽을 분산시킬 경우를 생각하면 편합니다.

서버 A와 B가 있다고 했을 때, 사용자 U가 서버 A에서 로그인하여 세션 인증을 했다고 가정해봅시다.
만약 서버 A가 문제가 생겨 다운되었을 경우 사용자 U는 서버 B에서 다시 로그인하여 세션 인증을 진행해야 합니다.
서버 A와 B는 서로 단절되어있기 때문에 서버 B에는 서버 A에서 진행한 세션이 기록되어있지 않아요.

이와 같이 로드밸런싱으로 api 분산 처리를 할 경우 토큰 방식이 세션 방식에 비해 더 관리하기 편합니다.

**Comment by hh830** [comment]
그럼 반대로 세션을 사용할 경우는 여러 개의 서버가 필요하지 않을 때, 비교적 가벼운 프로젝트일 때 사용한다고 이해하면 될까요?

**Comment by dnya0** [comment]
그보다는 비즈니스적으로 생각해서 판단하는게 좋습니다.
세션은 서버에서 관리하지만 토큰은 클라이언트에서 관리하여 서버 부하가 적다.
이 얘기는 보안상으로는 토큰보다 세션이 더 좋다는 이야기입니다.

따라서 보안이 중요하거나, 사용자의 계정 공유를 관리해야 하거나, 계정에 연결된 디바이스를 관리해야하거나 등의 기능이 필요하다면 세션을 쓰는 것이 좋을 수 있습니다.

토큰과 세션 중 한 가지만 사용하는 것이 아닌 토큰을 세션처럼 사용하거나, 토큰과 세션을 동시에 사용하는 방식으로 구현하여 세션, 토큰의 단점을 보완하는 방법도 있습니다.

저는 토큰을 세션처럼 사용하는 방식으로만 구현해봤는데요. 토큰을 액세스 용도와 재발급 용도로 2개 발급하여 액세스 토큰의 기간을 짧게, 재발급 토큰의 기간을 길게 주면 세션 방식으로 사용할 수 있습니다.

어떤 기능을 어떻게 구현하느냐의 차이라 정답이 없어요.

**Comment by hh830** [comment]
너무 멋있어요 감사합니다~!~! 🤩
